version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mueble_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: mueblesdb
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mueble-net

  app:
    build: .
    container_name: mueble_app
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      MYSQL_URL: ${MYSQL_URL}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
    networks:
      - mueble-net

volumes:
  mysql_data:

networks:
  mueble-net:
    driver: bridge